default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        my_periodic_job:
          class: MyJob
          args: [ 42, { status: "custom_status" } ]
          schedule: "*/5 * * * *"
  workers:
   - queues: "*"
     threads: 5
     processes: 1
     polling_interval: 0.1
development:
<<: *default

test:
<<: *default

production:
  <<: *default
